# Generated by Django 5.2.4 on 2025-07-28 03:27

import django.db.models.deletion
import utensil.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('unified_uuid', models.UUIDField(db_index=True, default=utensil.models.create_uuid, editable=False, unique=True, verbose_name='统一UUID标识')),
                ('uuid', models.UUIDField(default=utensil.models.create_uuid, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('username', models.CharField(db_index=True, help_text='用户名', max_length=150)),
                ('email', models.EmailField(blank=True, help_text='唯一邮箱', max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, help_text='唯一手机号', max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('is_staff', models.BooleanField(default=False, help_text='是否为后台管理员')),
                ('is_superuser', models.BooleanField(default=False, help_text='是否为超级管理员')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'account_user',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('unified_uuid', models.UUIDField(db_index=True, default=utensil.models.create_uuid, editable=False, unique=True, verbose_name='统一UUID标识')),
                ('uuid', models.UUIDField(default=utensil.models.create_uuid, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(help_text='角色名称', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='角色描述', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, help_text='角色权限', related_name='custom_roles', to='auth.permission')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'account_role',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='所属角色', related_name='users', to='account.role'),
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('unified_uuid', models.UUIDField(db_index=True, default=utensil.models.create_uuid, editable=False, unique=True, verbose_name='统一UUID标识')),
                ('uuid', models.UUIDField(default=utensil.models.create_uuid, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('code', models.CharField(help_text='系统唯一标识', max_length=50, unique=True)),
                ('name', models.CharField(help_text='系统名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='系统说明', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_systems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '系统',
                'verbose_name_plural': '系统',
                'db_table': 'account_system',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='account.system'),
        ),
        migrations.AddField(
            model_name='user',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.system'),
        ),
    ]
