# Generated by Django 5.2.4 on 2025-07-28 06:35

import utensil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='unified_uuid',
            field=models.CharField(db_index=True, default=utensil.models.create_uuid, editable=False, max_length=25, unique=True, verbose_name='统一UUID标识'),
        ),
        migrations.AlterField(
            model_name='role',
            name='uuid',
            field=models.CharField(default=utensil.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='system',
            name='unified_uuid',
            field=models.CharField(db_index=True, default=utensil.models.create_uuid, editable=False, max_length=25, unique=True, verbose_name='统一UUID标识'),
        ),
        migrations.AlterField(
            model_name='system',
            name='uuid',
            field=models.CharField(default=utensil.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unified_uuid',
            field=models.CharField(db_index=True, default=utensil.models.create_uuid, editable=False, max_length=25, unique=True, verbose_name='统一UUID标识'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=utensil.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
